version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - 3306:3306
  app:
    image: piwik:fpm
    links:
      - db
    volumes:
      - ./config:/var/www/html/config
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    ports:
      - 80:80
